apiVersion: "config.istio.io/v1alpha2"
kind: ServiceRole
metadata:
  name: service-viewer
  namespace: default
spec:
  rules:
  - services: ["*"]
    methods: ["GET","POST"]
    constraints:
    - key: "app"
      values: ["portal","service-a","service-b","service-c"]
---
apiVersion: "config.istio.io/v1alpha2"
kind: ServiceRoleBinding
metadata:
  name: bind-service-viewer
  namespace: default
spec:
  subjects:
  - properties:
      namespace: "default"
  - properties:
      namespace: "istio-system"
  roleRef:
    kind: ServiceRole
    name: "service-viewer"
