---

server:
  port: 8080
  contextPath: "/portal"


service:
  a:
    url: "http://localhost:8081/sa/info"
    method: "post"
  c:
    url: "http://localhost:8083/sc/info"
    method: "post"


spring:
  sleuth:
    sampler:
      percentage: "1.0"